### ISSUE TITLE
Make drop target larger

### ISSUE THREAD

**Issue by russellweed** [capira12/snapdrop#12]
Right now the blue circle you drop files onto and/or click/tap to select a file to upload is very small.

On desktops, you should really be able to drop a file anywhere on the page (white background) to upload, rather than forcing the user to drop only on the very small icon.

From a mobile device, likewise the button area should be larger to press; even if the logo stays the same size, a good portion of "background" should respond to tap events, making the app easier to use.

**Comment by capira12** [comment]
Thanks a lot for this comment. I really like the suggestions! I have implemented this. Does it work for you as expected?

**Comment by russellweed** [comment]
Perfect.
