### ISSUE TITLE
Feature Request: Name your device

### ISSUE THREAD

**Issue by russellweed** [capira12/snapdrop#13]
Other devices show up as "iOS Device", "Windows Firefox", etc. If you are on a larger wifi network (school or work) and not just your home network, this can use several identical devices to show up.

It would be better if you could name your own device, such as "Luke's iPhone" and "Ben's PC".

**Comment by henleygarcia** [comment]
Yes, please make this happen. I have so many computers  that I can't tell which is which except for the browser they're in.

**Comment by capira12** [comment]
@russellweed @henleygarcia what do you think about this solution?

**Comment by russellweed** [comment]
Beautiful. Naming my device worked wonderfully across Firefox (Windows), Chrome (Windows), my iPhone, and my iPad.

I have found one big error though; when I close the Snapdrop tab and re-opened it in Firefox, the site fails to load. Instead, it looks like its trying to dump a binary to my browser. Or perhaps text w/ the completely wrong encoding?

![firefox_snapdrop](https://cloud.githubusercontent.com/assets/1160446/12962803/9f03655c-d00c-11e5-8bad-aa5f9b219afb.PNG)

Shift+Refresh to clear the cache fixes things temporarily, but if I close the tab and open Snapdrop.net again I will get the error again. I cannot reproduce this error in Windows Chrome or iPhone/iPad.

Here's a text copy of the gibberish, just in case it means anything to you:

`��ks�6��� ���ḋd�N��Is����S��>d2�\��I�@Ѫ��~��hQ���Μg��}c_��A�2�n�������e�E��p<���`9�J� ��k�2z�m��אz9�L�� %=�)iA"��M�UÄa\2�f�:�fV1��4K�l)*01�(���VkfP0Q�L�V"���Bd��J�d�ie�a%2�����AL-V�B�.!k��؀d������#�6�[�B�M�k�J@�(mG�t"�e�ˋ܆ )��Ud2^A:�'!�����zj h��I�+� �[��qbZa+���ߟ���*�L�jf�e"#Ǘ����+����n��J�%�e�ڑ�����W��7�]s)�`��v���F�]���MS����GWx����:~�� �Z j��"B�(� 9iD��K1C����v��=bį`Ro���-�S��J�j�2�J��%nU���Y�\V�ȣ�1�̆QBx��3���mש��7�|dTimc�$�ل@,�&��0M�M�9 {Q'�_���7E���#AO"�ւ�?븽g��Z|��aa���Ѯw,*��� .���mx����~6&�"�۾�L�x|�amv���[�E��LՍ2�s�)S��$52���������:�?;v����]?�G������x+�D[*�i�����N��}�핁 +�1��-�A�����ϖi������,�p�ܯ�Za�\a�S�-�����Ef�����y��%�M�vB檋��Z�_*�a��'���!��&��t�����f2��'�&�M'�7g��.m��0O�H�Y�on���߆u8�� ��������L��B�������Z�2��OO_��H&cvA�L����N=],���#/'�4�Bs��]��2���/���A80�i�����VGTU�*��'Ȭ?A��l����`2{=�3ytX?{!�ʯ�`V��-p�/���tN��|��ѵ��Q���ёƆ�%�܊�_ZlTo%& !|ИX���S��a�]�Z������o�?�w��ő�JԀ1�K���l<<��<�Ѭ���f�L�C���q���f��1� ���RT���(�)�]v��&<=ï�P�X���kaT�Z� c$.����s�b�s98@j��JGT��p�L�c��tl�2���B��E�mښ�C�c�Ѫs�z�@^���p�{����:W���!ڎxX%8�Q���QI������c��Đ�%Am����6K���}f�s ���R!���N�[ḁ5+Óԛ �[lY:7I6���3Nl��^6��b5?o82�z� t(2�9`�����p�"�A~E�l�F�v ����hIv��h� ���V�����l,��sR�ٽo���d���g�5?��?����x������\�V�[��p=�L&[��}��g%ZQc�У{�t���؀w��Jz�4 V��b��7L-�T��}��B��ߡ�0xu��V=�� �J�Έ ��F4Q�1�(�.�����^;��,��X�y�9��_#�!j$�UU{��Qk�q�\9�jK�|@-y[�~oŚ��;y�?�LX�"���=;���@��� lpFP��lRE���qA3q=$��ү �O4X���4�m"d�zėc2|r|���!џ�|��� �J^�q00?.�1u�����O��s϶-g�� &��� *.�� nZS�\�J����!�+���LB�ޣ�Xq8��'�_����`�� ���W����Q?O����n�"yc :A�T� �����r����~���w>tx����� (d��E�*I����`L���c�d��6�Z�C4�q-��[K�y����>���i4%����=�j���� �؇��0H]�fB����璪}�`

**Comment by capira12** [comment]
Thanks!
